### ISSUE TITLE
Unable to reach ganache-cli in a docker container

### ISSUE THREAD

**Issue by SalahAdDin** [Alethio/memento#18]
Hi,

I'm trying to integrate `ganache-cli` to the _memento_ stack using a container, you can see my compose file here:
```
version: "3.7"
services:
  redis:
    container_name: memento-redis
    image: redis:5.0.5-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - .volumes/redis:/data
  postgres:
    container_name: memento-postgres
    image: postgres:11.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=memento
      - POSTGRES_DB=memento
      - POSTGRES_PASSWORD=password
    volumes:
      - .volumes/postgresql:/var/lib/postgresql/data
  ganache-cli:
    image: trufflesuite/ganache-cli
    container_name: ganache-cli
    ports:
      - 8545:8545
      - 8546:8546
  memento:
    container_name: memento
    image: alethio/memento:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 127.0.0.1:3001:3001
      - 127.0.0.1:3000:3000
    environment:
      - PG_PASSWORD=password
    volumes:
      - .volumes/memento:/config
  explorer:
    container_name: memento-lite-explorer
    image: alethio/ethereum-lite-explorer:latest
    restart: always
    depends_on:
      - memento
      - ganache-cli
    ports:
      - 127.0.0.1:80:80
    environment:
      - APP_NODE_URL="http://127.0.0.1:8545"
    volumes:
      - .volumes/lite-explorer/config.json:/usr/share/nginx/html/config.json
```

I can't get connected [_memento_](https://alethio.gitbook.io/memento/example-setups/ganache) and [_explorer_](https://github.com/Alethio/ethereum-lite-explorer#running-in-docker) despite i'm following the [documentation](https://alethio.gitbook.io/memento/running-memento/bundled-with-lite-explorer).

I tried disabling the [`docker`](https://github.com/trufflesuite/ganache-cli#docker) environment variable but it unables me to reach _ganache-cli_ container from my local machine.
Can anyone help me?
Thanks
